all:
	g++ src/emp.cpp -lwsock32 -lwinmm -std=c++11 -o dist/emp
	g++ src/blot.cpp -lwsock32 -std=c++11 -o dist/blot

game:
	g++ src/game.cpp -std=c++11 -o dist/game

calc:
	g++ src/calc.cpp -std=c++11 -o dist/calc

